// <auto-generated />
namespace StudyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class test22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test22));
        
        string IMigrationMetadata.Id
        {
            get { return "202407212100368_test22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
